### ISSUE TITLE
[Question] PlatformIO and client certificate

### ISSUE THREAD

**Issue by GMagician** [theelims/PsychicMqttClient#3]
Two questions:
1) Is supposed to work with client certificates? I Just see how to load CA cert
2) Is this supposed to be used with Platformio? 
  I get:
    UnknownPackageError: Could not find the package with 'theelims/PsychicMqttClient' requirements for your system 'windows_amd64'
  using:
    theelims/PsychicMqttClient
  as lib_deps

Thanks

**Comment by theelims** [comment]
Yes, this works with client certificates. You can either let the PlatformIO build system download and embed a certificate bundle, supply your own certificate or embed it a as string in the source files.

It is not yet registered with platformio as a library. You must use `https://github.com/theelims/PsychicMqttClient.git#0.1.1` under lib_deps.

**Comment by GMagician** [comment]
> It is not yet registered with platformio as a library. You must use `https://github.com/theelims/PsychicMqttClient.git#0.1.1` under lib_deps.

This is what I already did to solve, thanks for your reply

**Comment by theelims** [comment]
@GMagician I just published the library to the PlatformIO registry: https://registry.platformio.org/libraries/elims/PsychicMqttClient

You can use `theelims/PsychicMqttClient` now.

**Comment by GMagician** [comment]
thanks
