### ISSUE TITLE
Get disconnect reason

### ISSUE THREAD

**Issue by NilsRo** [theelims/PsychicMqttClient#9]
Hi,

I like to move to another client from AsyncMqttClient and your implementation looks great. The only thing I am missing is a disconnect reason in the callback. For error analysis it was helpful to me many times to provide this in my web interfaces. Would it be possible to get it somehow?

Cheers,
Nils

https://github.com/NilsRo/ImpulseSmartMeter/blob/bae77ff3915ed0e811c1c8ed736909271ef5142c/src/main.cpp#L502-L525

**Comment by theelims** [comment]
Hi,

have you checked the onError Callback? It gives access to the complete error object of the ESP-IDF:

https://github.com/espressif/esp-mqtt/blob/cea7e959eee68fc974fcae92572a1c37eca72d06/include/mqtt_client.h#L170

Which also contains the disconnect reason. With a little digging through the code from the link above you should be able to identify the disconnect reason.
